#ifndef JOLT_IOS_H
#define JOLT_IOS_H

/* Generated with cbindgen:0.29.2 */

/* Warning: This file is autogenerated by cbindgen. Don't modify directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace jolt {
#endif  // __cplusplus

/**
 * Status codes for FFI operations
 */
typedef enum jolt_status_code {
  SUCCESS = 0,
  ERROR_INVALID_INPUT = 1,
  ERROR_PROOF_GENERATION = 2,
  ERROR_VERIFICATION = 3,
  ERROR_SERIALIZATION = 4,
  ERROR_OUT_OF_MEMORY = 5,
  ERROR_NOT_IMPLEMENTED = 99,
} jolt_status_code;

/**
 * Transcript choice for prover/verifier
 */
enum JoltTranscriptFlavor
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  BLAKE2B = 0,
  KECCAK = 1,
};
#ifndef __cplusplus
typedef uint32_t JoltTranscriptFlavor;
#endif // __cplusplus

/**
 * Result structure for proof generation
 */
typedef struct jolt_proof_result {
  enum jolt_status_code status;
  uint64_t cycles;
  uint8_t *proof_data;
  uintptr_t proof_len;
  uint8_t *output_data;
  uintptr_t output_len;
} jolt_proof_result;

/**
 * Result structure for verification
 */
typedef struct jolt_verify_result {
  enum jolt_status_code status;
  bool is_valid;
} jolt_verify_result;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free memory allocated by Jolt
 *
 * # Safety
 * - `ptr` must have been allocated by this library
 * - `ptr` and `len` must match a previous allocation
 * - Must only be called once per allocation
 */
void jolt_free_buffer(uint8_t *ptr, uintptr_t len);

/**
 * Generate a proof for the supplied ELF and inputs.
 *
 * All buffers passed to this function must remain valid for the duration of the call.
 * The returned proof and output buffers are owned by the caller, who must free them
 * with [`jolt_free_buffer`].
 */
struct jolt_proof_result jolt_prove(const unsigned char *elf_bytes,
                                    uintptr_t elf_len,
                                    const unsigned char *input_bytes,
                                    uintptr_t input_len,
                                    uintptr_t max_input_size,
                                    uintptr_t max_output_size,
                                    uintptr_t max_trace_length,
                                    JoltTranscriptFlavor transcript);

/**
 * Verify a proof.
 *
 * The caller must pass the same transcript flavor, memory limits, and ELF that were used
 * when generating the proof.
 */
struct jolt_verify_result jolt_verify(const unsigned char *proof_data,
                                      uintptr_t proof_len,
                                      const unsigned char *elf_bytes,
                                      uintptr_t elf_len,
                                      const unsigned char *input_bytes,
                                      uintptr_t input_len,
                                      const unsigned char *output_bytes,
                                      uintptr_t output_len,
                                      uintptr_t max_input_size,
                                      uintptr_t max_output_size,
                                      uintptr_t max_trace_length,
                                      JoltTranscriptFlavor transcript);

/**
 * Get the version string
 *
 * Returns a null-terminated C string. Do NOT free this string.
 */
const char *jolt_version(void);

/**
 * Get a description of the current build configuration
 *
 * Returns a null-terminated C string. Do NOT free this string.
 */
const char *jolt_build_info(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace jolt
#endif  // __cplusplus

#endif  /* JOLT_IOS_H */
