//! Sparse row-matrix evaluations for the binary-field RV64I protocol.

use jolt_field::{JoltField, F128};
use jolt_r1cs::{ConstraintMatrices, SparseRow};
use jolt_rv64i_arith::{Layout, RowSystem, WITNESS_COLUMNS};

use crate::points::{eq_table, PointsError};

/// The two row blocks share the sparse matrices generated by `RowSystem`.
/// Evaluating both blocks allocates only their equality tables and the
/// 1,024-entry column equality table, independent of the trace length.
#[derive(Clone)]
pub struct RowMatrices {
    matrices: ConstraintMatrices<F128>,
    f128_row_variables: usize,
}

pub struct RowEvaluations<F> {
    pub blocks: [[F; 3]; 2],
    pub public_columns: F,
}

impl RowMatrices {
    pub fn new(layout: &Layout) -> Self {
        let rows = RowSystem::new(layout);
        let f128_row_variables = Self::block_variables(&rows);
        let matrices = rows.to_matrices();
        Self {
            matrices,
            f128_row_variables,
        }
    }

    /// Returns the extension row dimension without materializing matrices.
    pub fn f128_row_variables_for(layout: &Layout) -> usize {
        Self::block_variables(&RowSystem::new(layout))
    }

    fn block_variables(rows: &RowSystem) -> usize {
        (rows.num_rows() - RowSystem::F2_ROWS)
            .next_power_of_two()
            .ilog2() as usize
    }

    pub fn matrices(&self) -> &ConstraintMatrices<F128> {
        &self.matrices
    }

    pub fn f128_row_variables(&self) -> usize {
        self.f128_row_variables
    }

    /// Returns `[A, B, C]` at each block's row point and the shared column
    /// point, with the binary row block first. Each nonzero entry costs at
    /// most two field multiplications; unit coefficients cost one.
    pub fn evaluate<F: JoltField>(
        &self,
        rho_f2: &[F],
        rho_f128: &[F],
        column_point: &[F],
    ) -> Result<RowEvaluations<F>, PointsError> {
        for (point, expected) in [
            (rho_f2, 8),
            (rho_f128, self.f128_row_variables),
            (column_point, WITNESS_COLUMNS.ilog2() as usize),
        ] {
            if point.len() != expected {
                return Err(PointsError::Dimension {
                    expected,
                    actual: point.len(),
                });
            }
        }
        let f2_weights = eq_table(rho_f2)?;
        let f128_weights = eq_table(rho_f128)?;
        let column_weights = eq_table(column_point)?;
        let mut f2 = [F::zero(); 3];
        let mut f128 = [F::zero(); 3];
        for ((f2_value, f128_value), matrix) in
            f2.iter_mut()
                .zip(&mut f128)
                .zip([&self.matrices.a, &self.matrices.b, &self.matrices.c])
        {
            for (index, row) in matrix.iter().enumerate() {
                let (weights, index, variables, value) = if index < RowSystem::F2_ROWS {
                    (&f2_weights, index, rho_f2.len(), &mut *f2_value)
                } else {
                    (
                        &f128_weights,
                        index - RowSystem::F2_ROWS,
                        rho_f128.len(),
                        &mut *f128_value,
                    )
                };
                let row_weight = weights
                    .get(index)
                    .ok_or(PointsError::Index { index, variables })?;
                *value += evaluate_row(row, *row_weight, &column_weights)?;
            }
        }
        let public_columns = column_weights
            .first()
            .copied()
            .ok_or(PointsError::MissingColumn { column: 0 })?
            + column_weights
                .get(16)
                .copied()
                .ok_or(PointsError::MissingColumn { column: 16 })?;
        Ok(RowEvaluations {
            blocks: [f2, f128],
            public_columns,
        })
    }
}

fn evaluate_row<F: JoltField>(
    row: &SparseRow<F128>,
    row_weight: F,
    column_weights: &[F],
) -> Result<F, PointsError> {
    row.iter()
        .try_fold(F::zero(), |value, &(column, coefficient)| {
            let column_weight = column_weights
                .get(column)
                .ok_or(PointsError::MissingColumn { column })?;
            let weight = row_weight * *column_weight;
            Ok(value
                + if coefficient.to_raw() == 1 {
                    weight
                } else {
                    F::from_u128_reduced(coefficient.to_raw()) * weight
                })
        })
}
