//! Sparse row-matrix evaluations for the binary-field RV64I protocol.

use jolt_field::{JoltField, F128};
use jolt_r1cs::ConstraintMatrices;
use jolt_rv64i_arith::{Layout, RowSystem, WITNESS_COLUMNS};

use crate::points::{eq_table, PointsError};

/// The two row blocks share the sparse matrices generated by `RowSystem`.
/// Evaluating both blocks allocates only their equality tables and the
/// 1,024-entry column equality table, independent of the trace length.
#[derive(Clone)]
pub struct RowMatrices {
    matrices: ConstraintMatrices<F128>,
    f128_row_variables: usize,
}

pub struct RowEvaluations<F> {
    pub blocks: [[F; 3]; 2],
    pub public_columns: F,
}

impl RowMatrices {
    pub fn new(layout: &Layout) -> Self {
        let rows = RowSystem::new(layout);
        let f128_row_variables = Self::f128_row_variables_for(layout);
        let matrices = rows.to_matrices();
        Self {
            matrices,
            f128_row_variables,
        }
    }

    /// Returns the extension row dimension without materializing matrices.
    pub fn f128_row_variables_for(layout: &Layout) -> usize {
        RowSystem::f128_row_variables_for(layout)
    }

    pub fn matrices(&self) -> &ConstraintMatrices<F128> {
        &self.matrices
    }

    pub fn f128_row_variables(&self) -> usize {
        self.f128_row_variables
    }

    /// Returns `[A, B, C]` at each block's row point and the shared column
    /// point, with the binary row block first. Each nonzero entry costs at
    /// most two field multiplications; unit coefficients cost one.
    pub fn evaluate<F: JoltField>(
        &self,
        rho_f2: &[F],
        rho_f128: &[F],
        column_point: &[F],
    ) -> Result<RowEvaluations<F>, PointsError> {
        for (point, expected) in [
            (rho_f2, 8),
            (rho_f128, self.f128_row_variables),
            (column_point, WITNESS_COLUMNS.ilog2() as usize),
        ] {
            if point.len() != expected {
                return Err(PointsError::Dimension {
                    expected,
                    actual: point.len(),
                });
            }
        }
        let f2_weights = eq_table(rho_f2)?;
        let f128_weights = eq_table(rho_f128)?;
        let column_weights = eq_table(column_point)?;
        let mut blocks = [[F::zero(); 3]; 2];
        self.visit_entries(&f2_weights, &f128_weights, |block, side, column, value| {
            let column_weight = column_weights
                .get(column)
                .ok_or(PointsError::MissingColumn { column })?;
            let total = blocks
                .get_mut(block)
                .and_then(|values| values.get_mut(side))
                .ok_or(PointsError::MissingColumn { column })?;
            *total += value * *column_weight;
            Ok(())
        })?;
        let public_columns = column_weights
            .first()
            .copied()
            .ok_or(PointsError::MissingColumn { column: 0 })?
            + column_weights
                .get(16)
                .copied()
                .ok_or(PointsError::MissingColumn { column: 16 })?;
        Ok(RowEvaluations {
            blocks,
            public_columns,
        })
    }

    /// Folds the sparse row blocks into their six column tables. This dense
    /// public-domain table is consumed by the reference witness reduction.
    pub fn column_evaluations<F: JoltField>(
        &self,
        rho_f2: &[F],
        rho_f128: &[F],
    ) -> Result<Vec<[[F; 3]; 2]>, PointsError> {
        for (point, expected) in [(rho_f2, 8), (rho_f128, self.f128_row_variables)] {
            if point.len() != expected {
                return Err(PointsError::Dimension {
                    expected,
                    actual: point.len(),
                });
            }
        }
        let f2_weights = eq_table(rho_f2)?;
        let f128_weights = eq_table(rho_f128)?;
        let mut columns = vec![[[F::zero(); 3]; 2]; WITNESS_COLUMNS];
        self.visit_entries(&f2_weights, &f128_weights, |block, side, column, value| {
            let total = columns
                .get_mut(column)
                .and_then(|values| values.get_mut(block))
                .and_then(|values| values.get_mut(side))
                .ok_or(PointsError::MissingColumn { column })?;
            *total += value;
            Ok(())
        })?;
        Ok(columns)
    }

    fn visit_entries<F: JoltField>(
        &self,
        f2_weights: &[F],
        f128_weights: &[F],
        mut visit: impl FnMut(usize, usize, usize, F) -> Result<(), PointsError>,
    ) -> Result<(), PointsError> {
        for (side, matrix) in [&self.matrices.a, &self.matrices.b, &self.matrices.c]
            .into_iter()
            .enumerate()
        {
            for (index, row) in matrix.iter().enumerate() {
                let (block, weights, index) = if index < RowSystem::F2_ROWS {
                    (0, f2_weights, index)
                } else {
                    (1, f128_weights, index - RowSystem::F2_ROWS)
                };
                let row_weight = weights.get(index).copied().ok_or(PointsError::Index {
                    index,
                    variables: weights.len().ilog2() as usize,
                })?;
                for &(column, coefficient) in row {
                    if column >= WITNESS_COLUMNS {
                        return Err(PointsError::MissingColumn { column });
                    }
                    let value = if coefficient.to_raw() == 1 {
                        row_weight
                    } else {
                        F::from_u128_reduced(coefficient.to_raw()) * row_weight
                    };
                    visit(block, side, column, value)?;
                }
            }
        }
        Ok(())
    }
}
