//! Unified prover for the recursion SNARK protocol
//!
//! This module provides a high-level prover that orchestrates:
//! - Stage 1: Packed GT exp sumcheck
//! - Stage 2: Batched constraint sumchecks (shift + claim reduction + remaining constraints)
//! - Stage 3: Prefix packing reduction to a single dense polynomial opening
//!
//! The prover returns a proof and opening accumulator for PCS verification.

use ark_bn254::{Fq, Fr};
use ark_ec::CurveGroup;
use ark_ff::Zero;
use ark_grumpkin::Projective as GrumpkinProjective;
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use dory::backends::arkworks::{ArkGT, BN254};
use dory::recursion::ast::{AstGraph, AstOp};
use dory::recursion::WitnessCollection;
use jolt_optimizations::get_g_mle;
use std::collections::HashMap;

use crate::field::JoltField;
use crate::poly::commitment::commitment_scheme::{CommitmentScheme, RecursionExt};
use crate::poly::commitment::dory::instance_plan::{
    resolve_input_g1, resolve_input_g2, resolve_input_gt,
};
use crate::poly::commitment::dory::recursion::JoltWitness;
use crate::poly::commitment::dory::{
    wrappers::ArkDoryProof, ArkworksVerifierSetup, DoryCommitmentScheme,
};
use crate::poly::commitment::hyrax::{
    matrix_dimensions, Hyrax, HyraxCommitment, PedersenGenerators,
};
use crate::poly::dense_mlpoly::DensePolynomial;
use crate::poly::multilinear_polynomial::MultilinearPolynomial;
use crate::poly::opening_proof::{
    OpeningAccumulator, Openings, ProverOpeningAccumulator, SumcheckId,
};
use crate::poly::rlc_utils::compute_rlc_coefficients;
use crate::subprotocols::sumcheck::{BatchedSumcheck, SumcheckInstanceProof};
use crate::subprotocols::sumcheck_prover::SumcheckInstanceProver;
use crate::transcripts::Transcript;
use crate::zkvm::guest_serde::{GuestDeserialize, GuestSerialize};
use crate::zkvm::proof_serialization::PairingBoundary;
use crate::zkvm::witness::{
    CommittedPolynomial, G1AddTerm, G1ScalarMulTerm, G2AddTerm, G2ScalarMulTerm, GtExpTerm,
    GtMulTerm, RecursionPoly, VirtualPolynomial,
};

use super::constraints::system::{ConstraintSystem, PolyType};
use super::g1::addition::G1AddProver;
use super::g1::indexing::k_g1;
use super::g1::scalar_multiplication::{G1ScalarMulProver, ShiftG1ScalarMulProver};
use super::g1::wiring::WiringG1Prover;
use super::g2::addition::G2AddProver;
use super::g2::indexing::k_g2;
use super::g2::scalar_multiplication::{G2ScalarMulProver, ShiftG2ScalarMulProver};
use super::g2::wiring::WiringG2Prover;
use super::gt::base_power::GtExpBasePowProver;
use super::gt::exponentiation::{GtExpParams, GtExpProver};
use super::gt::indexing::{
    k_gt, num_gt_constraints, num_gt_constraints_padded, num_gt_mul_constraints_padded,
};
use super::gt::multiplication::{GtMulParams, GtMulProver};
use super::gt::shift::{GtShiftParams, GtShiftProver};
use super::gt::stage1_base_openings::GtExpBaseStage1OpeningsProver;
use super::gt::stage2_base_openings::GtExpBaseStage2OpeningsProver;
use super::gt::stage2_openings::GtExpStage2OpeningsProver;
use super::gt::types::GtMulConstraintPolynomials;
use super::gt::wiring::WiringGtProver;
use super::prefix_packing::{packed_eval_from_claims, PrefixPackingLayout};
use super::wiring_plan::{derive_wiring_plan, G1ValueRef, G2ValueRef, GtProducer};
use super::witness::GTCombineWitness;
use super::witness_generation;
use super::RecursionConstraintMetadata;
/// Proof generated by the recursion SNARK
#[derive(Clone, Debug, CanonicalSerialize, CanonicalDeserialize)]
pub struct RecursionProof<F: JoltField, T: Transcript, PCS: CommitmentScheme<Field = F>> {
    /// Stage 1: Packed GT exp sumcheck proof
    pub stage1_proof: SumcheckInstanceProof<F, T>,
    /// Stage 2: Batched constraint sumchecks proof.
    ///
    /// Includes:
    /// - packed-GT-exp internal consistency (shift rho)
    /// - packed-GT-exp claim reduction to a shared `r_x`
    /// - all other constraint families (GT mul, G1/G2 scalar mul, G1/G2 add, ...)
    pub stage2_proof: SumcheckInstanceProof<F, T>,
    /// Stage 3: Prefix-packed evaluation claim \(F(r_x \| r_{\mathrm{pack}})\).
    pub stage3_packed_eval: F,
    /// PCS opening proof for the constraint matrix
    pub opening_proof: PCS::Proof,
    /// Opening claims for virtual polynomials
    pub opening_claims: Openings<F>,
    /// Dense polynomial commitment after Stage 3 prefix packing.
    pub dense_commitment: PCS::Commitment,
}

impl<F, T, PCS> GuestSerialize for RecursionProof<F, T, PCS>
where
    F: JoltField + GuestSerialize,
    F::Challenge: GuestSerialize,
    PCS: CommitmentScheme<Field = F>,
    PCS::Proof: GuestSerialize,
    PCS::Commitment: GuestSerialize,
    T: Transcript,
{
    fn guest_serialize<W: std::io::Write>(&self, w: &mut W) -> std::io::Result<()> {
        self.stage1_proof.guest_serialize(w)?;
        self.stage2_proof.guest_serialize(w)?;
        self.stage3_packed_eval.guest_serialize(w)?;
        self.opening_proof.guest_serialize(w)?;
        self.opening_claims.guest_serialize(w)?;
        self.dense_commitment.guest_serialize(w)?;
        Ok(())
    }
}

impl<F, T, PCS> GuestDeserialize for RecursionProof<F, T, PCS>
where
    F: JoltField + GuestDeserialize,
    F::Challenge: GuestDeserialize,
    PCS: CommitmentScheme<Field = F>,
    PCS::Proof: GuestDeserialize,
    PCS::Commitment: GuestDeserialize,
    T: Transcript,
{
    fn guest_deserialize<R: std::io::Read>(r: &mut R) -> std::io::Result<Self> {
        Ok(Self {
            stage1_proof: SumcheckInstanceProof::<F, T>::guest_deserialize(r)?,
            stage2_proof: SumcheckInstanceProof::<F, T>::guest_deserialize(r)?,
            stage3_packed_eval: F::guest_deserialize(r)?,
            opening_proof: PCS::Proof::guest_deserialize(r)?,
            opening_claims: Openings::<F>::guest_deserialize(r)?,
            dense_commitment: PCS::Commitment::guest_deserialize(r)?,
        })
    }
}

/// Result type for recursion proof generation.
///
/// Contains the proof and constraint metadata needed by the verifier.
pub type RecursionProofResult<T, PCS> =
    Result<(RecursionProof<Fq, T, PCS>, RecursionConstraintMetadata), Box<dyn std::error::Error>>;

pub(crate) type HyraxPCS = Hyrax<1, GrumpkinProjective>;

pub(crate) struct HyraxPolyCommitPhaseOutput {
    pub(crate) metadata: RecursionConstraintMetadata,
    pub(crate) dense_commitment: HyraxCommitment<1, GrumpkinProjective>,
    pub(crate) dense_mlpoly: MultilinearPolynomial<Fq>,
}

pub(crate) struct SumcheckPhaseOutput<T: Transcript> {
    pub(crate) stage1_proof: SumcheckInstanceProof<Fq, T>,
    pub(crate) stage2_proof: SumcheckInstanceProof<Fq, T>,
    pub(crate) stage3_packed_eval: Fq,
    pub(crate) accumulator: ProverOpeningAccumulator<Fq>,
}

/// Unified prover for the recursion SNARK
#[derive(Clone)]
pub struct RecursionProver<F: JoltField = Fq> {
    /// The constraint system containing all constraints and witness data
    pub constraint_system: ConstraintSystem,
    /// Cached prefix-packed dense polynomial (emitted from stores).
    pub(crate) dense_poly_cache: Option<DensePolynomial<Fq>>,
    /// Cached prefix-packing layout (publicly derivable from `constraint_types`).
    pub(crate) prefix_layout_cache: Option<PrefixPackingLayout>,
    /// AST graph for wiring constraints (optional, only present when using AST-enabled mode)
    pub ast: Option<AstGraph<BN254>>,
    /// Pairing boundary outputs (bound by wiring/boundary constraints once enabled).
    pub pairing_boundary: Option<PairingBoundary>,
    /// Stage-8 joint commitment value (Fq12), bound to combine-commitments GT ops once wiring is enabled.
    pub joint_commitment: Option<ark_bn254::Fq12>,
    /// Boundary GT inputs (u32 `ValueId.0` -> Fq12) used by GT wiring constraints.
    pub gt_inputs: Option<Vec<(u32, ark_bn254::Fq12)>>,
    /// Boundary G1 inputs (u32 `ValueId.0` -> G1Affine) used by G1 wiring constraints.
    pub g1_inputs: Option<Vec<(u32, ark_bn254::G1Affine)>>,
    /// Boundary G2 inputs (u32 `ValueId.0` -> G2Affine) used by G2 wiring constraints.
    pub g2_inputs: Option<Vec<(u32, ark_bn254::G2Affine)>>,
    /// Number of leaf commitments in the Stage-8 combine DAG.
    pub combine_leaves: usize,
    /// Phantom for field type
    _marker: std::marker::PhantomData<F>,
}

/// Recursion-agnostic snapshot of the Stage 8 (Dory) opening state needed to kick off recursion proving.
///
/// This is produced by Stage 8 (batch opening proof) without performing any recursion-only work.
///
/// CRITICAL transcript invariant:
/// - `pre_opening_proof_transcript` must be forked from the main transcript **after** all Stage 8
///   claims have been appended and gamma has been sampled, but **before** `PCS::prove` mutates
///   the main transcript. This fork is what `PCS::witness_gen` must use (it mutates transcripts).
#[derive(Clone)]
pub struct DoryOpeningSnapshot<F: JoltField, ProofTranscript: Transcript> {
    /// Forked transcript state right after gamma sampling (before `PCS::prove`).
    pub pre_opening_proof_transcript: ProofTranscript,
    /// Unified opening point (big-endian challenges).
    pub opening_point: Vec<<F as JoltField>::Challenge>,
    /// Ordered (polynomial, claim) pairs used for Stage 8 RLC (with any embedding factors applied).
    ///
    /// Order matters: this must match the claim ordering used to sample gamma powers.
    pub polynomial_claims: Vec<(CommittedPolynomial, F)>,
    /// Gamma powers sampled from the transcript after appending all claims.
    pub gamma_powers: Vec<F>,
    /// Joint claim: Σ γ_i · claim_i.
    pub joint_claim: F,
}

/// Bundle of Stage 8 artifacts needed to start recursion proving.
///
/// This removes parameter sprawl at the Stage8→recursion boundary and makes it harder
/// to accidentally desynchronize proof/setup/snapshot inputs.
pub struct RecursionInput<'a, F: JoltField, PCS: RecursionExt<F>, ProofTranscript: Transcript> {
    pub joint_opening_proof: &'a PCS::Proof,
    pub stage8_snapshot: DoryOpeningSnapshot<F, ProofTranscript>,
    pub verifier_setup: &'a PCS::VerifierSetup,
    pub commitments: &'a HashMap<CommittedPolynomial, PCS::Commitment>,
}

impl RecursionProver<Fq> {
    /// Phase 1: witness generation for recursion proving.
    ///
    /// Performs all recursion-only work needed to start recursion proving from the Stage 8 (Dory) opening:
    /// - combine witness generation (Stage 8 offload) + serialized `stage8_combine_hint`
    /// - `PCS::witness_gen_with_ast` (Stage 9) + symbolic AST capture
    /// - build the recursion constraint system and return `RecursionProver`
    #[allow(clippy::type_complexity)]
    #[tracing::instrument(skip_all, name = "RecursionProver::witness_generation")]
    fn witness_generation<F, PCS, ProofTranscript>(
        input: RecursionInput<'_, F, PCS, ProofTranscript>,
    ) -> Result<(Self, ark_bn254::Fq12, PCS::Ast, PairingBoundary), Box<dyn std::error::Error>>
    where
        F: JoltField,
        PCS: RecursionExt<F, Witness = WitnessCollection<JoltWitness>, Ast = AstGraph<BN254>>
            + CommitmentScheme<
                Field = F,
                Proof = ArkDoryProof,
                VerifierSetup = ArkworksVerifierSetup,
                Commitment = ArkGT,
            >,
        ProofTranscript: Transcript,
        PCS::CombineHint: Send,
    {
        let joint_opening_proof = input.joint_opening_proof;
        let verifier_setup = input.verifier_setup;

        // Stage 8 (recursion-only): compute joint commitment (value-only).
        let DoryOpeningSnapshot {
            pre_opening_proof_transcript,
            opening_point,
            polynomial_claims,
            gamma_powers,
            joint_claim,
        } = input.stage8_snapshot;

        let rlc_map = compute_rlc_coefficients(&gamma_powers, polynomial_claims);

        let mut coeffs = Vec::with_capacity(rlc_map.len());
        let mut comms = Vec::with_capacity(rlc_map.len());
        for (poly, coeff) in rlc_map.into_iter() {
            let commitment = input
                .commitments
                .get(&poly)
                .ok_or_else(|| format!("Missing commitment for Stage 8 polynomial {poly:?}"))?;
            coeffs.push(coeff);
            comms.push(*commitment);
        }

        let joint_commitment = PCS::combine_commitments(&comms, &coeffs);

        // Phase E3: overlap combine-witness generation with Stage 9 witness generation.
        //
        // Both are expensive but independent once `joint_commitment` is known.
        let (combine_out, witness_out) = rayon::join(
            || {
                tracing::info_span!(
                    "stage8_generate_combine_witness",
                    num_commitments = comms.len()
                )
                .in_scope(|| PCS::generate_combine_witness(&comms, &coeffs))
            },
            || {
                let mut witness_gen_transcript = pre_opening_proof_transcript;
                tracing::info_span!(
                    "stage9_witness_gen_with_ast",
                    opening_point_len = opening_point.len()
                )
                .in_scope(|| {
                    PCS::witness_gen_with_ast(
                        joint_opening_proof,
                        verifier_setup,
                        &mut witness_gen_transcript,
                        &opening_point,
                        &joint_claim,
                        &joint_commitment,
                    )
                })
            },
        );

        let (combine_witness, combine_hint) = combine_out;
        let stage8_combine_hint_fq12 = PCS::combine_hint_to_fq12(&combine_hint);
        let (witness_collection, ast) =
            witness_out.map_err(|e| Box::new(e) as Box<dyn std::error::Error>)?;

        // Phase F (pairing boundary): derive boundary from the (fully realized) AST and Stage 8 inputs.
        //
        // This is later re-derived by the verifier from a symbolic AST for binding.
        let pairing_boundary = PCS::derive_pairing_boundary_from_ast(
            &ast,
            joint_opening_proof,
            verifier_setup,
            joint_commitment,
            &comms,
            &coeffs,
        )
        .map_err(|e| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("AST->pairing-boundary derivation failed: {e}"),
            )
        })?;

        // Resolve any GT-valued AST inputs that feed directly into GT ports (e.g. GTMul lhs/rhs).
        //
        // These are used by the GT wiring sumcheck as verifier-derived boundary constants.
        let wiring_for_inputs = derive_wiring_plan(&ast, comms.len(), &pairing_boundary, &[])
            .map_err(|e| {
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("AST->wiring-plan derivation failed: {e}"),
                )
            })?;
        let dory_setup: dory::setup::VerifierSetup<BN254> = verifier_setup.clone().into();
        let mut gt_input_ids: Vec<u32> = wiring_for_inputs
            .gt
            .iter()
            .filter_map(|e| match e.src {
                GtProducer::GtInput { value_id } => Some(value_id),
                _ => None,
            })
            .collect();
        gt_input_ids.sort();
        gt_input_ids.dedup();
        let mut gt_inputs: Vec<(u32, ark_bn254::Fq12)> = Vec::with_capacity(gt_input_ids.len());
        for value_id in gt_input_ids {
            let idx = value_id as usize;
            let node = ast.nodes.get(idx).ok_or_else(|| {
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("gt_input value_id {value_id} out of bounds"),
                )
            })?;
            let AstOp::Input { source } = &node.op else {
                return Err(Box::new(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("gt_input value_id {value_id} is not an AstOp::Input"),
                )));
            };
            let v = resolve_input_gt(joint_opening_proof, &dory_setup, joint_commitment, source)
                .map_err(|e| {
                    Box::new(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        format!("gt_input resolve failed for value_id {value_id}: {e}"),
                    )) as Box<dyn std::error::Error>
                })?;
            gt_inputs.push((value_id, v.0));
        }
        let mut g1_input_ids: Vec<u32> = wiring_for_inputs
            .g1
            .iter()
            .flat_map(|e| [e.src, e.dst])
            .filter_map(|v| match v {
                G1ValueRef::G1Input { value_id } => Some(value_id),
                _ => None,
            })
            .collect();
        g1_input_ids.sort();
        g1_input_ids.dedup();
        let mut g1_inputs: Vec<(u32, ark_bn254::G1Affine)> = Vec::with_capacity(g1_input_ids.len());
        for value_id in g1_input_ids {
            let idx = value_id as usize;
            let node = ast.nodes.get(idx).ok_or_else(|| {
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("g1_input value_id {value_id} out of bounds"),
                )
            })?;
            let AstOp::Input { source } = &node.op else {
                return Err(Box::new(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("g1_input value_id {value_id} is not an AstOp::Input"),
                )));
            };
            let p = resolve_input_g1(joint_opening_proof, &dory_setup, source)
                .map_err(|e| {
                    Box::new(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        format!("g1_input resolve failed for value_id {value_id}: {e}"),
                    )) as Box<dyn std::error::Error>
                })?
                .0
                .into_affine();
            g1_inputs.push((value_id, p));
        }
        let mut g2_input_ids: Vec<u32> = wiring_for_inputs
            .g2
            .iter()
            .flat_map(|e| [e.src, e.dst])
            .filter_map(|v| match v {
                G2ValueRef::G2Input { value_id } => Some(value_id),
                _ => None,
            })
            .collect();
        g2_input_ids.sort();
        g2_input_ids.dedup();
        let mut g2_inputs: Vec<(u32, ark_bn254::G2Affine)> = Vec::with_capacity(g2_input_ids.len());
        for value_id in g2_input_ids {
            let idx = value_id as usize;
            let node = ast.nodes.get(idx).ok_or_else(|| {
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("g2_input value_id {value_id} out of bounds"),
                )
            })?;
            let AstOp::Input { source } = &node.op else {
                return Err(Box::new(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("g2_input value_id {value_id} is not an AstOp::Input"),
                )));
            };
            let p = resolve_input_g2(joint_opening_proof, &dory_setup, source)
                .map_err(|e| {
                    Box::new(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        format!("g2_input resolve failed for value_id {value_id}: {e}"),
                    )) as Box<dyn std::error::Error>
                })?
                .0
                .into_affine();
            g2_inputs.push((value_id, p));
        }

        // Build constraint system from generated witnesses and include combine witness constraints.
        let mut prover = Self::new_from_witnesses(witness_collection, Some(combine_witness))?;
        prover.pairing_boundary = Some(pairing_boundary.clone());
        prover.joint_commitment = Some(stage8_combine_hint_fq12);
        prover.gt_inputs = Some(gt_inputs);
        prover.g1_inputs = Some(g1_inputs);
        prover.g2_inputs = Some(g2_inputs);

        Ok((prover, stage8_combine_hint_fq12, ast, pairing_boundary))
    }

    /// Full Stage8→recursion pipeline entrypoint.
    ///
    /// This is the definitive call for recursion proving:
    /// 1) `witness_generation` (Stage 8 offload + Stage 9 `witness_gen` + build CS)\n
    /// 2) `poly_commit` (Hyrax commit)\n
    /// 3) `prove_sumchecks` (all recursion sumchecks)\n
    /// 4) `poly_opening` (Hyrax opening)\n
    ///
    /// Returns the recursion proof and internal verifier metadata.
    #[allow(clippy::type_complexity)]
    pub fn prove<F, DoryPCS, ProofTranscript>(
        transcript: &mut ProofTranscript,
        hyrax_prover_setup: &PedersenGenerators<GrumpkinProjective>,
        input: RecursionInput<'_, F, DoryPCS, ProofTranscript>,
    ) -> Result<
        (
            RecursionProof<Fq, ProofTranscript, HyraxPCS>,
            RecursionConstraintMetadata,
            PairingBoundary,
            Option<ark_bn254::Fq12>,
        ),
        Box<dyn std::error::Error>,
    >
    where
        F: JoltField,
        DoryPCS: RecursionExt<F, Witness = WitnessCollection<JoltWitness>, Ast = AstGraph<BN254>>
            + CommitmentScheme<
                Field = F,
                Proof = ArkDoryProof,
                VerifierSetup = ArkworksVerifierSetup,
                Commitment = ArkGT,
            >,
        DoryPCS::CombineHint: Send,
        ProofTranscript: Transcript,
    {
        // Phase 1: witness generation
        let (mut prover, stage8_combine_hint_fq12, ast, pairing_boundary) =
            Self::witness_generation::<F, DoryPCS, ProofTranscript>(input)?;
        prover.ast = Some(ast);

        // Pairing recursion: add MultiMillerLoop + GTMul chain constraints once the pairing boundary is known.
        prover.append_pairing_recursion_constraints()?;

        // Phase 2: polynomial commitment (Hyrax)
        let poly_commit = prover.poly_commit::<ProofTranscript>(transcript, hyrax_prover_setup)?;

        // Phase 3: sumchecks
        let sumchecks =
            prover.prove_sumchecks::<ProofTranscript>(transcript, &poly_commit.metadata)?;

        // Phase 4: polynomial opening (Hyrax)
        let (opening_proof, opening_claims) = Self::poly_opening::<ProofTranscript, HyraxPCS>(
            transcript,
            hyrax_prover_setup,
            sumchecks.accumulator,
            poly_commit.dense_mlpoly,
        )?;

        let proof = RecursionProof {
            stage1_proof: sumchecks.stage1_proof,
            stage2_proof: sumchecks.stage2_proof,
            stage3_packed_eval: sumchecks.stage3_packed_eval,
            opening_proof,
            opening_claims,
            dense_commitment: poly_commit.dense_commitment,
        };

        Ok((
            proof,
            poly_commit.metadata,
            pairing_boundary,
            Some(stage8_combine_hint_fq12),
        ))
    }

    /// Create a new recursion prover from pre-generated witnesses
    pub fn new_from_witnesses(
        witness_collection: WitnessCollection<JoltWitness>,
        combine_witness: Option<GTCombineWitness>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        tracing::debug!(
            "Creating RecursionProver from witnesses: GT exp count = {}, GT mul count = {}",
            witness_collection.gt_exp.len(),
            witness_collection.gt_mul.len()
        );

        // Compute g_poly directly (was previously computed in witnesses_to_dory_recursion)
        // g(x) is the irreducible polynomial defining the Fq12 extension field
        let g_poly = {
            let g_mle_4var = get_g_mle();
            // Keep `g(x)` in its native 4-var form (size 16). Any embeddings are handled
            // locally by the specific constraint family.
            DensePolynomial::new(g_mle_4var)
        };

        // Build constraint system from witness collection using DoryMatrixBuilder
        let build_cs_span = tracing::info_span!("build_constraint_system").entered();
        let combine_leaves = combine_witness
            .as_ref()
            .map(|cw| cw.exp_witnesses.len())
            .unwrap_or(0);
        let constraint_system =
            Self::build_constraint_system(witness_collection, combine_witness, g_poly)?;
        drop(build_cs_span);

        Ok(Self {
            constraint_system,
            dense_poly_cache: None,
            prefix_layout_cache: None,
            ast: None,
            pairing_boundary: None,
            joint_commitment: None,
            gt_inputs: None,
            g1_inputs: None,
            g2_inputs: None,
            combine_leaves,
            _marker: std::marker::PhantomData,
        })
    }

    /// Create a new recursion prover by generating witnesses from a Dory proof
    pub fn new_from_dory_proof<T: Transcript>(
        dory_proof: &ArkDoryProof,
        verifier_setup: &ArkworksVerifierSetup,
        transcript: &mut T,
        point: &[<Fr as JoltField>::Challenge],
        evaluation: &Fr,
        commitment: &ArkGT,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        // Use Dory's witness_gen to generate witnesses
        let (witness_collection, _ast) = DoryCommitmentScheme::witness_gen_with_ast(
            dory_proof,
            verifier_setup,
            transcript,
            point,
            evaluation,
            commitment,
        )?;

        // Delegate to new_from_witnesses (no combine_witness from direct Dory proof)
        Self::new_from_witnesses(witness_collection, None)
    }

    /// Create a new recursion prover with AST tracing enabled.
    ///
    /// This captures the full computation DAG, enabling:
    /// Build constraint system from recursion witness
    fn build_constraint_system(
        witness_collection: WitnessCollection<JoltWitness>,
        combine_witness: Option<GTCombineWitness>,
        g_poly: DensePolynomial<Fq>,
    ) -> Result<ConstraintSystem, Box<dyn std::error::Error>> {
        witness_generation::plan_constraint_system(witness_collection, combine_witness, g_poly)
    }
}

impl RecursionProver<Fq> {
    fn append_pairing_recursion_constraints(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        use crate::poly::commitment::dory::witness::{
            gt_mul::MultiplicationSteps, multi_miller_loop::MultiMillerLoopSteps,
        };
        use crate::zkvm::recursion::constraints::system::{
            ConstraintLocator, ConstraintType, GtMulNativeRows, MultiMillerLoopNativeRows,
        };
        use jolt_optimizations::fq12_to_multilinear_evals;

        // Require pairing boundary (derived from AST) to be present.
        let pairing = self
            .pairing_boundary
            .as_ref()
            .ok_or("pairing_boundary missing when adding pairing recursion constraints")?;

        let g1s = [pairing.p1_g1, pairing.p2_g1, pairing.p3_g1];
        let g2s = [pairing.p1_g2, pairing.p2_g2, pairing.p3_g2];

        // Build the per-pair Miller loop traces (packed 11-var MLEs).
        let steps = MultiMillerLoopSteps::new(&g1s, &g2s);
        if steps.pair_results.len() != 3 {
            return Err("expected exactly 3 Miller loop pairs in PairingBoundary".into());
        }
        if std::env::var_os("JOLT_DEBUG_CHECK_MILLER_RHS").is_some() {
            // Sanity check: the pairing boundary's pre-final-exponentiation Miller product must
            // match the product of the per-pair traces we are about to commit/wire.
            if pairing.miller_rhs != steps.result {
                return Err(format!(
                    "pairing_boundary.miller_rhs mismatch: boundary != product(trace outputs)"
                )
                .into());
            }
        }

        // Append 3 MultiMillerLoop constraints (one per pairing pair).
        for i in 0..3 {
            let local = self.constraint_system.multi_miller_loop_rows.len();
            self.constraint_system
                .constraint_types
                .push(ConstraintType::MultiMillerLoop);
            self.constraint_system
                .locator_by_constraint
                .push(ConstraintLocator::MultiMillerLoop { local });

            self.constraint_system
                .multi_miller_loop_rows
                .push(MultiMillerLoopNativeRows {
                    f: steps.f_packed_mles[i].clone(),
                    f_next: steps.f_next_packed_mles[i].clone(),
                    quotient: steps.quotient_packed_mles[i].clone(),
                    t_x_c0: steps.t_x_c0_packed_mles[i].clone(),
                    t_x_c1: steps.t_x_c1_packed_mles[i].clone(),
                    t_y_c0: steps.t_y_c0_packed_mles[i].clone(),
                    t_y_c1: steps.t_y_c1_packed_mles[i].clone(),
                    t_x_c0_next: steps.t_x_c0_next_packed_mles[i].clone(),
                    t_x_c1_next: steps.t_x_c1_next_packed_mles[i].clone(),
                    t_y_c0_next: steps.t_y_c0_next_packed_mles[i].clone(),
                    t_y_c1_next: steps.t_y_c1_next_packed_mles[i].clone(),
                    lambda_c0: steps.lambda_c0_packed_mles[i].clone(),
                    lambda_c1: steps.lambda_c1_packed_mles[i].clone(),
                    inv_delta_x_c0: steps.inv_dx_c0_packed_mles[i].clone(),
                    inv_delta_x_c1: steps.inv_dx_c1_packed_mles[i].clone(),
                    inv_two_y_c0: steps.inv_two_y_c0_packed_mles[i].clone(),
                    inv_two_y_c1: steps.inv_two_y_c1_packed_mles[i].clone(),
                    x_p: steps.x_p_packed_mles[i].clone(),
                    y_p: steps.y_p_packed_mles[i].clone(),
                    x_q_c0: steps.x_q_c0_packed_mles[i].clone(),
                    x_q_c1: steps.x_q_c1_packed_mles[i].clone(),
                    y_q_c0: steps.y_q_c0_packed_mles[i].clone(),
                    y_q_c1: steps.y_q_c1_packed_mles[i].clone(),
                    is_double: steps.is_double_packed_mles[i].clone(),
                    is_add: steps.is_add_packed_mles[i].clone(),
                    l_val: steps.l_val_packed_mles[i].clone(),
                });
        }

        // Append GTMul constraints to multiply the 3 Miller outputs into one Fq12.
        //
        // mul0 = out0 * out1
        // mul1 = mul0 * out2
        let out0 = steps.pair_results[0];
        let out1 = steps.pair_results[1];
        let out2 = steps.pair_results[2];

        let mul0 = MultiplicationSteps::new(out0, out1);
        let mul1 = MultiplicationSteps::new(mul0.result, out2);

        if std::env::var_os("JOLT_DEBUG_CHECK_MML_WIRING_VALUES").is_some() {
            // These should match exactly: the GT mul constraints we append are meant to be wired
            // directly from the per-pair Miller outputs.
            if mul0.lhs != out0 || mul0.rhs != out1 {
                return Err("pairing recursion mul0 inputs mismatch".into());
            }
            if mul1.lhs != mul0.result || mul1.rhs != out2 {
                return Err("pairing recursion mul1 inputs mismatch".into());
            }
            // And the product must match the (verifier-visible) pairing boundary miller_rhs.
            if mul1.result != pairing.miller_rhs {
                return Err("pairing recursion miller_rhs != mul1.result".into());
            }
        }

        for mul in [mul0, mul1] {
            let local = self.constraint_system.gt_mul_rows.len();
            self.constraint_system
                .constraint_types
                .push(ConstraintType::GtMul);
            self.constraint_system
                .locator_by_constraint
                .push(ConstraintLocator::GtMul { local });
            self.constraint_system.gt_mul_rows.push(GtMulNativeRows {
                lhs: fq12_to_multilinear_evals(&mul.lhs),
                rhs: fq12_to_multilinear_evals(&mul.rhs),
                result: fq12_to_multilinear_evals(&mul.result),
                quotient: mul.quotient_mle,
            });
        }

        // Update the public shape (used by verifier metadata) and invalidate cached commitments.
        self.constraint_system.recompute_shape();
        self.dense_poly_cache = None;
        self.prefix_layout_cache = None;
        Ok(())
    }

    #[tracing::instrument(skip_all, name = "RecursionProver::poly_commit")]
    pub(crate) fn poly_commit<T: Transcript>(
        &mut self,
        transcript: &mut T,
        prover_setup: &PedersenGenerators<GrumpkinProjective>,
    ) -> Result<HyraxPolyCommitPhaseOutput, Box<dyn std::error::Error>> {
        // IMPORTANT: Commitment must happen BEFORE sumchecks for soundness!
        if self.dense_poly_cache.is_none() || self.prefix_layout_cache.is_none() {
            let (dense_poly, prefix_layout) = tracing::info_span!("emit_prefix_packed_dense")
                .in_scope(|| {
                    tracing::info!("Emitting prefix-packed dense polynomial");
                    witness_generation::emit_dense(&self.constraint_system)
                });
            self.dense_poly_cache = Some(dense_poly);
            self.prefix_layout_cache = Some(prefix_layout);
        }

        let dense_poly = self
            .dense_poly_cache
            .as_ref()
            .expect("dense_poly_cache must be populated");
        let prefix_layout = self
            .prefix_layout_cache
            .as_ref()
            .expect("prefix_layout_cache must be populated");

        let dense_num_vars = prefix_layout.num_dense_vars;
        let unpadded_len = prefix_layout.unpadded_len();
        let padded_len = dense_poly.len();

        // Diagnostics for prefix packing.
        {
            let num_constraints = self.constraint_system.constraint_types.len();
            let num_gt_exp_ops = self.constraint_system.gt_exp_witnesses.len();
            let num_gt_mul_ops = self.constraint_system.gt_mul_rows.len();
            let num_gt = num_gt_constraints(&self.constraint_system.constraint_types);
            let num_gt_padded = num_gt_constraints_padded(&self.constraint_system.constraint_types);
            let k = k_gt(&self.constraint_system.constraint_types);
            tracing::info!(
                num_constraints,
                num_gt_exp_ops,
                num_gt_mul_ops,
                num_gt_constraints = num_gt,
                num_gt_constraints_padded = num_gt_padded,
                k_gt = k,
                dense_num_vars,
                unpadded_len,
                padded_len,
                "prefix packing stats"
            );
            for e in prefix_layout.entries.iter().filter(|e| e.is_gt) {
                tracing::info!(
                    ?e.poly_type,
                    e.num_vars,
                    native_size = (1usize << e.num_vars),
                    e.offset,
                    "GT packed entry"
                );
            }
        }

        // Log how much Hyrax work we skip by avoiding padded zeros.
        let (l_size, r_size) = matrix_dimensions(dense_num_vars, 1);
        debug_assert_eq!(l_size * r_size, padded_len);
        let used_rows = unpadded_len.div_ceil(r_size);
        let skipped_rows = l_size.saturating_sub(used_rows);
        tracing::info!(
            dense_num_vars,
            unpadded_len,
            padded_len,
            r_size,
            l_size,
            used_rows,
            skipped_rows,
            tail_elems = (unpadded_len % r_size),
            "Hyrax commit skipping zero-padded tail"
        );

        let metadata = tracing::info_span!("build_constraint_metadata").in_scope(|| {
            tracing::info!("Building constraint metadata for verifier");
            let constraint_types = self.constraint_system.constraint_types.clone();

            RecursionConstraintMetadata {
                constraint_types,
                dense_num_vars,
                gt_exp_public_inputs: self.constraint_system.gt_exp_public_inputs.clone(),
                g1_scalar_mul_public_inputs: self
                    .constraint_system
                    .g1_scalar_mul_public_inputs
                    .clone(),
                g2_scalar_mul_public_inputs: self
                    .constraint_system
                    .g2_scalar_mul_public_inputs
                    .clone(),
            }
        });

        // Hyrax commit (optimized): avoid MSM work on zero-padded suffix.
        let dense_commitment = HyraxCommitment::<1, GrumpkinProjective>::commit_with_unpadded_len(
            dense_poly,
            prover_setup,
            unpadded_len,
        );

        // Convert to multilinear polynomial for downstream sumchecks / opening proof.
        let dense_mlpoly = MultilinearPolynomial::from(dense_poly.evals());
        tracing::info!(
            "Hyrax commitment terms: {}, unpadded_len: {}",
            dense_mlpoly.len(),
            unpadded_len
        );

        // Add commitment to transcript for Fiat-Shamir soundness
        transcript.append_serializable(&dense_commitment);

        Ok(HyraxPolyCommitPhaseOutput {
            metadata,
            dense_commitment,
            dense_mlpoly,
        })
    }

    #[tracing::instrument(skip_all, name = "RecursionProver::prove_sumchecks")]
    pub(crate) fn prove_sumchecks<T: Transcript>(
        &mut self,
        transcript: &mut T,
        metadata: &RecursionConstraintMetadata,
    ) -> Result<SumcheckPhaseOutput<T>, Box<dyn std::error::Error>> {
        // Initialize opening accumulator
        let log_t = self.constraint_system.num_vars();
        let mut accumulator = tracing::info_span!("init_opening_accumulator").in_scope(|| {
            let acc = ProverOpeningAccumulator::<Fq>::new(log_t);
            tracing::info!("Initialized opening accumulator with {} variables", log_t);
            acc
        });

        // Stage 1: Packed GT exp sumcheck
        let (stage1_proof, _r_stage1_packed) = self
            .prove_stage1(transcript, &mut accumulator)
            .expect("Failed to run Stage 1 (GtExp)");

        // Stage 2: Batched constraint sumchecks
        let (stage2_proof, r_stage2) = self
            .prove_stage2(transcript, &mut accumulator)
            .expect("Failed to run Stage 2 (constraint sumchecks)");

        // Stage 2 challenges layout:
        // - `r_stage2` ends with `r_x` (length = num_constraint_vars)
        // - the prefix may include family-index variables (e.g. `c_gt`) depending on which
        //   constraint families are present
        //
        // NOTE: Recursion constraint sumchecks are **suffix-aligned** in the batched sumcheck
        // (`round_offset = max_num_rounds - num_rounds`), so shorter points are suffixes of longer
        // ones in the batched challenge order. We therefore interpret `r_x` as the **suffix** of
        // the Stage-2 challenge vector.
        let num_constraint_vars = self.constraint_system.num_constraint_vars();
        if r_stage2.len() < num_constraint_vars {
            return Err(format!(
                "Stage 2 returned {} challenges, expected at least {} (num_constraint_vars)",
                r_stage2.len(),
                num_constraint_vars,
            )
            .into());
        }
        // Interpret `r_x` as the suffix of length `num_constraint_vars`.
        let r_x_start = r_stage2.len() - num_constraint_vars;
        let _r_x = &r_stage2[r_x_start..];
        // If the Stage-2 point contains the GT-local `c_gt` suffix (length k_gt), it is the slice
        // immediately before `r_x`. Other family suffixes may exist, but are not interpreted here.
        let k = k_gt(&self.constraint_system.constraint_types);
        let _r_c_gt = if r_x_start >= k {
            &r_stage2[r_x_start - k..r_x_start]
        } else {
            &[][..]
        };

        // Stage 3: Prefix packing (direct reduction to a single Hyrax opening)
        let stage3_packed_eval = self
            .prove_stage3_prefix_packing(transcript, &mut accumulator, metadata, &r_stage2)
            .expect("Failed to run Stage 3 (prefix packing)");

        Ok(SumcheckPhaseOutput {
            stage1_proof,
            stage2_proof,
            stage3_packed_eval,
            accumulator,
        })
    }

    #[tracing::instrument(skip_all, name = "RecursionProver::poly_opening")]
    pub(crate) fn poly_opening<T: Transcript, PCS: CommitmentScheme<Field = Fq>>(
        transcript: &mut T,
        prover_setup: &PCS::ProverSetup,
        mut accumulator: ProverOpeningAccumulator<Fq>,
        dense_mlpoly: MultilinearPolynomial<Fq>,
    ) -> Result<(PCS::Proof, Openings<Fq>), Box<dyn std::error::Error>> {
        tracing::info!("Generating PCS opening proof");

        // Create polynomial map for opening proof
        let mut polynomials_map: HashMap<CommittedPolynomial, MultilinearPolynomial<Fq>> =
            HashMap::new();
        polynomials_map.insert(CommittedPolynomial::DoryDenseMatrix, dense_mlpoly);

        // Generate opening proof using PCS
        let opening_proof = accumulator
            .prove_single::<T, PCS>(polynomials_map, prover_setup, transcript)
            .expect("Failed to generate PCS opening proof");

        let opening_claims = accumulator.openings.clone();
        tracing::info!(
            "Generated opening proof with {} claims",
            opening_claims.len()
        );

        Ok((opening_proof, opening_claims))
    }

    /// Run Stage 1: Packed GT exp sumcheck
    #[allow(clippy::type_complexity)]
    #[tracing::instrument(skip_all, name = "RecursionProver::prove_stage1")]
    pub(crate) fn prove_stage1<T: Transcript>(
        &self,
        transcript: &mut T,
        accumulator: &mut ProverOpeningAccumulator<Fq>,
    ) -> Result<
        (
            SumcheckInstanceProof<Fq, T>,
            Vec<<Fq as JoltField>::Challenge>,
        ),
        Box<dyn std::error::Error>,
    > {
        let packed_witnesses = &self.constraint_system.gt_exp_witnesses;
        if packed_witnesses.is_empty() {
            return Err("No GtExp constraints to prove in Stage 1".into());
        }

        // Packed GT exp uses layout x * 128 + s (s in low bits), so g needs replication
        // across the step variables.
        fn pad_4var_to_11var_replicated(mle_4var: &[Fq]) -> Vec<Fq> {
            debug_assert_eq!(mle_4var.len(), 16, "Input must be a 4-variable MLE");
            let mut mle_11var = vec![Fq::zero(); 2048];
            // index = x * 128 + s (x in high 4 bits, s in low 7 bits)
            for x in 0..16 {
                let g_x = mle_4var[x];
                for s in 0..128 {
                    mle_11var[x * 128 + s] = g_x;
                }
            }
            mle_11var
        }

        let g_4var: Vec<Fq> = self.constraint_system.g_poly.evals();
        let g_replicated = pad_4var_to_11var_replicated(&g_4var);
        let g_poly_replicated_f = DensePolynomial::new(g_replicated);

        let params = GtExpParams::from_constraint_types(&self.constraint_system.constraint_types);
        tracing::info!(
            "[Stage 1] Creating GtExpProver with {} GTExp witnesses",
            packed_witnesses.len()
        );
        let mut packed_gt_exp_prover: Box<dyn SumcheckInstanceProver<Fq, T>> =
            Box::new(GtExpProver::new(
                params,
                &self.constraint_system.constraint_types,
                &self.constraint_system.locator_by_constraint,
                packed_witnesses,
                g_poly_replicated_f,
                transcript,
            ));

        let mut base_openings: Box<dyn SumcheckInstanceProver<Fq, T>> =
            Box::new(GtExpBaseStage1OpeningsProver::<T>::new(
                &self.constraint_system.constraint_types,
                &self.constraint_system.locator_by_constraint,
                packed_witnesses,
            ));

        // Run the batched sumcheck (ordering matters for cached openings).
        let (proof, r_stage1) = BatchedSumcheck::prove(
            vec![&mut *base_openings, &mut *packed_gt_exp_prover],
            accumulator,
            transcript,
        );

        Ok((proof, r_stage1))
    }

    /// Run Stage 2: Batched constraint sumchecks.
    ///
    /// This stage includes:
    /// - packed-GT-exp internal consistency (`GtShift`)
    /// - packed-GT-exp claim reduction to a shared `r_x`
    /// - all remaining constraint families (GT mul, G1/G2 scalar mul, G1/G2 add, ...)
    #[allow(clippy::type_complexity)]
    #[tracing::instrument(skip_all, name = "RecursionProver::prove_stage2")]
    pub(crate) fn prove_stage2<T: Transcript>(
        &self,
        transcript: &mut T,
        accumulator: &mut ProverOpeningAccumulator<Fq>,
    ) -> Result<
        (
            SumcheckInstanceProof<Fq, T>,
            Vec<<Fq as JoltField>::Challenge>, // r_stage2 = [r_c || r_x]
        ),
        Box<dyn std::error::Error>,
    > {
        let mut provers: Vec<Box<dyn SumcheckInstanceProver<Fq, T>>> = Vec::new();

        let num_gt_exp = self.constraint_system.gt_exp_witnesses.len();
        if num_gt_exp > 0 {
            // GTExp claim-reduction/openings must be available before the shift
            // verifier runs (ordering matters in `BatchedSumcheck::verify`).
            let prover = GtExpStage2OpeningsProver::<T>::new(
                &self.constraint_system.constraint_types,
                &self.constraint_system.locator_by_constraint,
                &self.constraint_system.gt_exp_witnesses,
            );
            provers.push(Box::new(prover));

            // Cache-only openings for committed GTExp base rows on the native u-domain.
            let prover = GtExpBaseStage2OpeningsProver::<T>::new(
                &self.constraint_system.constraint_types,
                &self.constraint_system.locator_by_constraint,
                &self.constraint_system.gt_exp_witnesses,
                transcript,
            );
            provers.push(Box::new(prover));

            // Enforce base2/base3 correctness without verifier recomputation.
            let prover = GtExpBasePowProver::new(
                &self.constraint_system.constraint_types,
                &self.constraint_system.locator_by_constraint,
                &self.constraint_system.gt_exp_witnesses,
                &self.constraint_system.g_poly,
                transcript,
            );
            provers.push(Box::new(prover));

            let params =
                GtShiftParams::from_constraint_types(&self.constraint_system.constraint_types);
            let prover = GtShiftProver::new(
                params,
                &self.constraint_system.constraint_types,
                &self.constraint_system.locator_by_constraint,
                &self.constraint_system.gt_exp_witnesses,
                accumulator,
            );
            provers.push(Box::new(prover));
        }

        // NOTE: GT mul / G1+G2 scalar mul / G1+G2 add were previously run in Stage 1;
        // we keep their logic but batch them here.

        // Convert g_poly for GT mul (uses zero padding layout: s * 16 + x)
        let g_poly_f = self.constraint_system.g_poly.clone();

        // GT mul
        //
        // NOTE (debugging): setting `JOLT_DEBUG_SKIP_GT_MUL=1` skips the GTMul sumcheck instance
        // (useful to isolate Stage-2 sumcheck failures).
        let gt_mul_rows = &self.constraint_system.gt_mul_rows;
        if std::env::var_os("JOLT_DEBUG_SKIP_GT_MUL").is_none() && !gt_mul_rows.is_empty() {
            let gt_mul_constraints_fq: Vec<GtMulConstraintPolynomials<Fq>> = gt_mul_rows
                .iter()
                .enumerate()
                .map(|(i, rows)| GtMulConstraintPolynomials {
                    lhs: rows.lhs.clone(),
                    rhs: rows.rhs.clone(),
                    result: rows.result.clone(),
                    quotient: rows.quotient.clone(),
                    constraint_index: i,
                })
                .collect();
            let num_gt_constraints = gt_mul_constraints_fq.len();
            let k_common = k_gt(&self.constraint_system.constraint_types);
            let num_gt_constraints_padded =
                num_gt_mul_constraints_padded(&self.constraint_system.constraint_types);
            let params = GtMulParams::new(num_gt_constraints, num_gt_constraints_padded, k_common);
            let prover = GtMulProver::new(
                params,
                &self.constraint_system.constraint_types,
                &gt_mul_constraints_fq,
                &g_poly_f,
                transcript,
            );
            provers.push(Box::new(prover));
        }

        // G1 scalar mul
        let g1_rows = &self.constraint_system.g1_scalar_mul_rows;
        if !g1_rows.is_empty() {
            debug_assert_eq!(
                self.constraint_system.g1_scalar_mul_public_inputs.len(),
                g1_rows.len(),
                "ConstraintSystem.g1_scalar_mul_public_inputs must match extracted G1 scalar-mul constraints"
            );

            let k_common = k_g1(&self.constraint_system.constraint_types);
            let prover = G1ScalarMulProver::new_with_k_common(
                g1_rows,
                &self.constraint_system.g1_scalar_mul_public_inputs,
                k_common,
                transcript,
            );
            provers.push(Box::new(prover));

            // Always run the shift check (it reuses scalar-mul cached openings).
            let prover = ShiftG1ScalarMulProver::new_with_k_common(g1_rows, k_common, transcript);
            provers.push(Box::new(prover));
        }

        // G2 scalar mul
        let g2_rows = &self.constraint_system.g2_scalar_mul_rows;
        if !g2_rows.is_empty() {
            debug_assert_eq!(
                self.constraint_system.g2_scalar_mul_public_inputs.len(),
                g2_rows.len(),
                "ConstraintSystem.g2_scalar_mul_public_inputs must match extracted G2 scalar-mul constraints"
            );

            let k_common = k_g2(&self.constraint_system.constraint_types);
            let prover = G2ScalarMulProver::new_with_k_common(
                g2_rows,
                &self.constraint_system.g2_scalar_mul_public_inputs,
                k_common,
                transcript,
            );
            provers.push(Box::new(prover));

            // Always run the shift check (it reuses scalar-mul cached openings).
            let prover = ShiftG2ScalarMulProver::new_with_k_common(g2_rows, k_common, transcript);
            provers.push(Box::new(prover));
        }

        // G1 add
        let g1_add_rows = &self.constraint_system.g1_add_rows;
        if !g1_add_rows.is_empty() {
            let prover = G1AddProver::new(g1_add_rows, transcript);
            provers.push(Box::new(prover));
        }

        // G2 add
        let g2_add_rows = &self.constraint_system.g2_add_rows;
        if !g2_add_rows.is_empty() {
            let prover = G2AddProver::new(g2_add_rows, transcript);
            provers.push(Box::new(prover));
        }

        // Pairing recursion: Multi-Miller loop + shift check (Stage 2; x-only, suffix-aligned).
        if !self.constraint_system.multi_miller_loop_rows.is_empty() {
            use crate::zkvm::recursion::pairing::multi_miller_loop::{
                FrontAlignedMultiMillerLoopProver, MultiMillerLoopParams, MultiMillerLoopProverSpec,
            };
            use crate::zkvm::recursion::pairing::shift::{
                ShiftMultiMillerLoopParams, ShiftMultiMillerLoopProver,
            };
            use crate::zkvm::witness::MultiMillerLoopTerm;

            let Some(pairing_boundary) = self.pairing_boundary.as_ref() else {
                return Err("pairing_boundary missing for pairing stage2".into());
            };
            if self.constraint_system.multi_miller_loop_rows.len() != 3 {
                return Err(format!(
                    "expected exactly 3 MultiMillerLoop rows, got {}",
                    self.constraint_system.multi_miller_loop_rows.len()
                )
                .into());
            }

            // Map MultiMillerLoop local -> global constraint index for VirtualPolynomial IDs.
            let mut global_idx_by_local =
                vec![None; self.constraint_system.multi_miller_loop_rows.len()];
            for (global_idx, loc) in self
                .constraint_system
                .locator_by_constraint
                .iter()
                .enumerate()
            {
                if let crate::zkvm::recursion::ConstraintLocator::MultiMillerLoop { local } = *loc {
                    global_idx_by_local[local] = Some(global_idx);
                }
            }
            let mut witnesses =
                Vec::with_capacity(self.constraint_system.multi_miller_loop_rows.len());
            let mut g1_points =
                Vec::with_capacity(self.constraint_system.multi_miller_loop_rows.len());
            let mut g2_points =
                Vec::with_capacity(self.constraint_system.multi_miller_loop_rows.len());
            for (local, rows) in self
                .constraint_system
                .multi_miller_loop_rows
                .iter()
                .enumerate()
            {
                let global_idx =
                    global_idx_by_local[local].ok_or("missing global idx for MultiMillerLoop")?;
                witnesses.push(
                    crate::zkvm::recursion::pairing::multi_miller_loop::MultiMillerLoopWitness::<
                        Fq,
                    > {
                        f: rows.f.clone(),
                        f_next: rows.f_next.clone(),
                        quotient: rows.quotient.clone(),
                        t_x_c0: rows.t_x_c0.clone(),
                        t_x_c1: rows.t_x_c1.clone(),
                        t_y_c0: rows.t_y_c0.clone(),
                        t_y_c1: rows.t_y_c1.clone(),
                        t_x_c0_next: rows.t_x_c0_next.clone(),
                        t_x_c1_next: rows.t_x_c1_next.clone(),
                        t_y_c0_next: rows.t_y_c0_next.clone(),
                        t_y_c1_next: rows.t_y_c1_next.clone(),
                        lambda_c0: rows.lambda_c0.clone(),
                        lambda_c1: rows.lambda_c1.clone(),
                        inv_delta_x_c0: rows.inv_delta_x_c0.clone(),
                        inv_delta_x_c1: rows.inv_delta_x_c1.clone(),
                        inv_two_y_c0: rows.inv_two_y_c0.clone(),
                        inv_two_y_c1: rows.inv_two_y_c1.clone(),
                        x_p: rows.x_p.clone(),
                        y_p: rows.y_p.clone(),
                        x_q_c0: rows.x_q_c0.clone(),
                        x_q_c1: rows.x_q_c1.clone(),
                        y_q_c0: rows.y_q_c0.clone(),
                        y_q_c1: rows.y_q_c1.clone(),
                        is_double: rows.is_double.clone(),
                        is_add: rows.is_add.clone(),
                        l_val: rows.l_val.clone(),
                        constraint_index: global_idx,
                    },
                );
                // Pairing boundary order is p1/p2/p3.
                g1_points.push(
                    [
                        pairing_boundary.p1_g1,
                        pairing_boundary.p2_g1,
                        pairing_boundary.p3_g1,
                    ][local],
                );
                g2_points.push(
                    [
                        pairing_boundary.p1_g2,
                        pairing_boundary.p2_g2,
                        pairing_boundary.p3_g2,
                    ][local],
                );
            }

            let params = MultiMillerLoopParams::new(witnesses.len());
            let (spec, constraint_indices) =
                MultiMillerLoopProverSpec::new(params, witnesses, g1_points, g2_points);
            let inner: crate::zkvm::recursion::pairing::MultiMillerLoopProver<Fq> = crate::zkvm::recursion::constraints::sumcheck::ConstraintListProver::<
                Fq,
                _,
                7,
            >::from_spec(spec, constraint_indices, transcript);
            let dummy_after_rounds = k_gt(&self.constraint_system.constraint_types);
            provers.push(Box::new(FrontAlignedMultiMillerLoopProver::new(
                inner,
                dummy_after_rounds,
            )));

            // Shift check for f and T coordinates (plus `*_next` columns).
            //
            // NOTE (debugging): setting `JOLT_DEBUG_SKIP_MML_SHIFT=1` skips this shift gadget to
            // isolate Stage-2 sumcheck failures to the core MultiMillerLoop constraint.
            if std::env::var_os("JOLT_DEBUG_SKIP_MML_SHIFT").is_none() {
                let mut pairs: Vec<(
                    crate::zkvm::witness::VirtualPolynomial,
                    Vec<Fq>,
                    crate::zkvm::witness::VirtualPolynomial,
                    Vec<Fq>,
                )> = Vec::new();
                for (local, rows) in self
                    .constraint_system
                    .multi_miller_loop_rows
                    .iter()
                    .enumerate()
                {
                    let global_idx = global_idx_by_local[local].expect("global idx must exist");
                    let mk = |term: MultiMillerLoopTerm| {
                        crate::zkvm::witness::VirtualPolynomial::multi_miller_loop(term, global_idx)
                    };
                    pairs.push((
                        mk(MultiMillerLoopTerm::F),
                        rows.f.clone(),
                        mk(MultiMillerLoopTerm::FNext),
                        rows.f_next.clone(),
                    ));
                    pairs.push((
                        mk(MultiMillerLoopTerm::TXC0),
                        rows.t_x_c0.clone(),
                        mk(MultiMillerLoopTerm::TXC0Next),
                        rows.t_x_c0_next.clone(),
                    ));
                    pairs.push((
                        mk(MultiMillerLoopTerm::TXC1),
                        rows.t_x_c1.clone(),
                        mk(MultiMillerLoopTerm::TXC1Next),
                        rows.t_x_c1_next.clone(),
                    ));
                    pairs.push((
                        mk(MultiMillerLoopTerm::TYC0),
                        rows.t_y_c0.clone(),
                        mk(MultiMillerLoopTerm::TYC0Next),
                        rows.t_y_c0_next.clone(),
                    ));
                    pairs.push((
                        mk(MultiMillerLoopTerm::TYC1),
                        rows.t_y_c1.clone(),
                        mk(MultiMillerLoopTerm::TYC1Next),
                        rows.t_y_c1_next.clone(),
                    ));
                }
                let params = ShiftMultiMillerLoopParams::new(pairs.len());
                let shift = ShiftMultiMillerLoopProver::<Fq, T>::new(params, pairs, transcript);
                provers.push(Box::new(shift));
            }
        }

        // Wiring/boundary constraints (AST-driven), appended LAST in Stage 2.
        //
        // NOTE (debugging): setting `JOLT_DEBUG_SKIP_RECURSION_WIRING=1` skips these constraints to
        // isolate Stage-2 sumcheck failures to the (non-wiring) constraint families.
        if std::env::var_os("JOLT_DEBUG_SKIP_RECURSION_WIRING").is_none() {
            if let (Some(ast), Some(pairing_boundary), Some(joint_commitment)) = (
                self.ast.as_ref(),
                self.pairing_boundary.as_ref(),
                self.joint_commitment.as_ref(),
            ) {
                let wiring = derive_wiring_plan(
                    ast,
                    self.combine_leaves,
                    pairing_boundary,
                    &self.constraint_system.constraint_types,
                )
                .map_err(|_e| "AST->wiring-plan derivation failed")?;

                if !wiring.gt.is_empty() {
                    let gt_inputs = self.gt_inputs.as_deref().unwrap_or(&[]);
                    let wiring_gt = WiringGtProver::<T>::new(
                        &self.constraint_system,
                        wiring.gt.clone(),
                        pairing_boundary,
                        *joint_commitment,
                        gt_inputs,
                        transcript,
                    );
                    provers.push(Box::new(wiring_gt));
                }
                if !wiring.g1.is_empty() {
                    let g1_inputs = self.g1_inputs.as_deref().unwrap_or(&[]);
                    provers.push(Box::new(WiringG1Prover::<T>::new(
                        &self.constraint_system,
                        wiring.g1.clone(),
                        pairing_boundary,
                        g1_inputs,
                        transcript,
                    )));
                }
                if !wiring.g2.is_empty() {
                    let g2_inputs = self.g2_inputs.as_deref().unwrap_or(&[]);
                    provers.push(Box::new(WiringG2Prover::<T>::new(
                        &self.constraint_system,
                        wiring.g2.clone(),
                        pairing_boundary,
                        g2_inputs,
                        transcript,
                    )));
                }
            }
        }

        if provers.is_empty() {
            return Err("No constraints to prove in Stage 2".into());
        }

        let (proof, r_stage2) = BatchedSumcheck::prove(
            provers.iter_mut().map(|p| &mut **p as _).collect(),
            accumulator,
            transcript,
        );

        Ok((proof, r_stage2))
    }

    /// Run Stage 3: Prefix packing reduction.
    ///
    /// This samples fresh "packing prefix" challenges and reduces all Stage 2 virtual openings
    /// to a single opening of the packed dense polynomial `CommittedPolynomial::DoryDenseMatrix`.
    #[tracing::instrument(skip_all, name = "RecursionProver::prove_stage3_prefix_packing")]
    pub(crate) fn prove_stage3_prefix_packing<T: Transcript>(
        &mut self,
        transcript: &mut T,
        accumulator: &mut ProverOpeningAccumulator<Fq>,
        metadata: &RecursionConstraintMetadata,
        r_stage2: &[<Fq as JoltField>::Challenge],
    ) -> Result<Fq, Box<dyn std::error::Error>> {
        // Derive the public packing layout.
        let layout = PrefixPackingLayout::from_constraint_types(&metadata.constraint_types);
        if layout.num_dense_vars != metadata.dense_num_vars {
            return Err(format!(
                "prefix packing layout mismatch: metadata.dense_num_vars={} but derived layout has {}",
                metadata.dense_num_vars, layout.num_dense_vars
            )
            .into());
        }

        let max_native_vars = layout.entries.iter().map(|e| e.num_vars).max().unwrap_or(0);
        if r_stage2.len() < max_native_vars {
            return Err(format!(
                "Stage 2 produced r_stage2 of length {}, but prefix packing needs at least {} bits",
                r_stage2.len(),
                max_native_vars
            )
            .into());
        }

        // Low variables: Stage-2 point suffix (suffix-aligned Stage 2), **reversed**.
        //
        // Stage 2 constraint sumchecks are suffix-aligned in the batched sumcheck, so an m-var
        // polynomial is opened at the *suffix* of the common challenge vector. For the
        // prefix-packing reduction we want these to appear as prefixes, so we reverse the suffix
        // here.
        let mut r_native_fq: Vec<Fq> = r_stage2[r_stage2.len() - max_native_vars..]
            .iter()
            .map(|c| (*c).into())
            .collect();
        r_native_fq.reverse();

        // High variables: fresh packing challenges.
        let pack_len = layout.num_dense_vars.saturating_sub(max_native_vars);
        let r_pack: Vec<Fq> = (0..pack_len)
            .map(|_| transcript.challenge_scalar::<Fq>())
            .collect();

        // Full packed opening point in little-endian (low-to-high) variable order.
        let mut r_full_lsb: Vec<Fq> = Vec::with_capacity(layout.num_dense_vars);
        r_full_lsb.extend_from_slice(&r_native_fq);
        r_full_lsb.extend_from_slice(&r_pack);

        // Compute packed evaluation claim: F(r) = Σ_i eq(prefix_i, codeword_i) · f_i(r_x_prefix).
        let packed_eval = packed_eval_from_claims(&layout, &r_full_lsb, |entry| {
            if entry.is_gt {
                let (sumcheck, vp) = match entry.poly_type {
                    PolyType::RhoPrev => (
                        SumcheckId::GtExpClaimReduction,
                        VirtualPolynomial::Recursion(RecursionPoly::GtExp {
                            term: GtExpTerm::Rho,
                        }),
                    ),
                    PolyType::Quotient => (
                        SumcheckId::GtExpClaimReduction,
                        VirtualPolynomial::Recursion(RecursionPoly::GtExp {
                            term: GtExpTerm::Quotient,
                        }),
                    ),
                    PolyType::GtExpBase => (
                        SumcheckId::GtExpBaseClaimReduction,
                        VirtualPolynomial::Recursion(RecursionPoly::GtExp {
                            term: GtExpTerm::Base,
                        }),
                    ),
                    PolyType::GtExpBase2 => (
                        SumcheckId::GtExpBaseClaimReduction,
                        VirtualPolynomial::Recursion(RecursionPoly::GtExp {
                            term: GtExpTerm::Base2,
                        }),
                    ),
                    PolyType::GtExpBase3 => (
                        SumcheckId::GtExpBaseClaimReduction,
                        VirtualPolynomial::Recursion(RecursionPoly::GtExp {
                            term: GtExpTerm::Base3,
                        }),
                    ),
                    PolyType::GtExpBaseSquareQuotient => (
                        SumcheckId::GtExpBaseClaimReduction,
                        VirtualPolynomial::Recursion(RecursionPoly::GtExp {
                            term: GtExpTerm::BaseSquareQuotient,
                        }),
                    ),
                    PolyType::GtExpBaseCubeQuotient => (
                        SumcheckId::GtExpBaseClaimReduction,
                        VirtualPolynomial::Recursion(RecursionPoly::GtExp {
                            term: GtExpTerm::BaseCubeQuotient,
                        }),
                    ),
                    PolyType::MulLhs => (
                        SumcheckId::GtMul,
                        VirtualPolynomial::Recursion(RecursionPoly::GtMul {
                            term: GtMulTerm::Lhs,
                        }),
                    ),
                    PolyType::MulRhs => (
                        SumcheckId::GtMul,
                        VirtualPolynomial::Recursion(RecursionPoly::GtMul {
                            term: GtMulTerm::Rhs,
                        }),
                    ),
                    PolyType::MulResult => (
                        SumcheckId::GtMul,
                        VirtualPolynomial::Recursion(RecursionPoly::GtMul {
                            term: GtMulTerm::Result,
                        }),
                    ),
                    PolyType::MulQuotient => (
                        SumcheckId::GtMul,
                        VirtualPolynomial::Recursion(RecursionPoly::GtMul {
                            term: GtMulTerm::Quotient,
                        }),
                    ),
                    _ => return Fq::zero(),
                };
                accumulator.get_virtual_polynomial_claim(vp, sumcheck)
            } else if entry.is_g1_scalar_mul {
                let vp = match entry.poly_type {
                    PolyType::G1ScalarMulXA => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::XA,
                        })
                    }
                    PolyType::G1ScalarMulYA => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::YA,
                        })
                    }
                    PolyType::G1ScalarMulXT => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::XT,
                        })
                    }
                    PolyType::G1ScalarMulYT => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::YT,
                        })
                    }
                    PolyType::G1ScalarMulXANext => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::XANext,
                        })
                    }
                    PolyType::G1ScalarMulYANext => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::YANext,
                        })
                    }
                    PolyType::G1ScalarMulTIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::TIndicator,
                        })
                    }
                    PolyType::G1ScalarMulAIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::AIndicator,
                        })
                    }
                    _ => return Fq::zero(),
                };
                accumulator.get_virtual_polynomial_claim(vp, SumcheckId::G1ScalarMul)
            } else if entry.is_g1_scalar_mul_base {
                let vp = match entry.poly_type {
                    PolyType::G1ScalarMulXP => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::XP,
                        })
                    }
                    PolyType::G1ScalarMulYP => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1ScalarMul {
                            term: G1ScalarMulTerm::YP,
                        })
                    }
                    _ => return Fq::zero(),
                };
                accumulator.get_virtual_polynomial_claim(vp, SumcheckId::G1ScalarMul)
            } else if entry.is_g1_add {
                let vp = match entry.poly_type {
                    PolyType::G1AddXP => VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                        term: G1AddTerm::XP,
                    }),
                    PolyType::G1AddYP => VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                        term: G1AddTerm::YP,
                    }),
                    PolyType::G1AddPIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                            term: G1AddTerm::PIndicator,
                        })
                    }
                    PolyType::G1AddXQ => VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                        term: G1AddTerm::XQ,
                    }),
                    PolyType::G1AddYQ => VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                        term: G1AddTerm::YQ,
                    }),
                    PolyType::G1AddQIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                            term: G1AddTerm::QIndicator,
                        })
                    }
                    PolyType::G1AddXR => VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                        term: G1AddTerm::XR,
                    }),
                    PolyType::G1AddYR => VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                        term: G1AddTerm::YR,
                    }),
                    PolyType::G1AddRIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                            term: G1AddTerm::RIndicator,
                        })
                    }
                    // Non-port terms are still packed for G1.
                    PolyType::G1AddLambda => VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                        term: G1AddTerm::Lambda,
                    }),
                    PolyType::G1AddInvDeltaX => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                            term: G1AddTerm::InvDeltaX,
                        })
                    }
                    PolyType::G1AddIsDouble => VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                        term: G1AddTerm::IsDouble,
                    }),
                    PolyType::G1AddIsInverse => {
                        VirtualPolynomial::Recursion(RecursionPoly::G1Add {
                            term: G1AddTerm::IsInverse,
                        })
                    }
                    _ => return Fq::zero(),
                };
                accumulator.get_virtual_polynomial_claim(vp, SumcheckId::G1Add)
            } else if entry.is_g2_scalar_mul {
                let vp = match entry.poly_type {
                    PolyType::G2ScalarMulXAC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XAC0,
                        })
                    }
                    PolyType::G2ScalarMulXAC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XAC1,
                        })
                    }
                    PolyType::G2ScalarMulYAC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YAC0,
                        })
                    }
                    PolyType::G2ScalarMulYAC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YAC1,
                        })
                    }
                    PolyType::G2ScalarMulXTC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XTC0,
                        })
                    }
                    PolyType::G2ScalarMulXTC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XTC1,
                        })
                    }
                    PolyType::G2ScalarMulYTC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YTC0,
                        })
                    }
                    PolyType::G2ScalarMulYTC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YTC1,
                        })
                    }
                    PolyType::G2ScalarMulXANextC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XANextC0,
                        })
                    }
                    PolyType::G2ScalarMulXANextC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XANextC1,
                        })
                    }
                    PolyType::G2ScalarMulYANextC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YANextC0,
                        })
                    }
                    PolyType::G2ScalarMulYANextC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YANextC1,
                        })
                    }
                    PolyType::G2ScalarMulTIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::TIndicator,
                        })
                    }
                    PolyType::G2ScalarMulAIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::AIndicator,
                        })
                    }
                    PolyType::G2ScalarMulXPC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XPC0,
                        })
                    }
                    PolyType::G2ScalarMulXPC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XPC1,
                        })
                    }
                    PolyType::G2ScalarMulYPC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YPC0,
                        })
                    }
                    PolyType::G2ScalarMulYPC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YPC1,
                        })
                    }
                    _ => return Fq::zero(),
                };
                accumulator.get_virtual_polynomial_claim(vp, SumcheckId::G2ScalarMul)
            } else if entry.is_g2_scalar_mul_base {
                let vp = match entry.poly_type {
                    PolyType::G2ScalarMulXPC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XPC0,
                        })
                    }
                    PolyType::G2ScalarMulXPC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::XPC1,
                        })
                    }
                    PolyType::G2ScalarMulYPC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YPC0,
                        })
                    }
                    PolyType::G2ScalarMulYPC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2ScalarMul {
                            term: G2ScalarMulTerm::YPC1,
                        })
                    }
                    _ => return Fq::zero(),
                };
                accumulator.get_virtual_polynomial_claim(vp, SumcheckId::G2ScalarMul)
            } else if entry.is_g2_add {
                let vp = match entry.poly_type {
                    PolyType::G2AddXPC0 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::XPC0,
                    }),
                    PolyType::G2AddXPC1 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::XPC1,
                    }),
                    PolyType::G2AddYPC0 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::YPC0,
                    }),
                    PolyType::G2AddYPC1 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::YPC1,
                    }),
                    PolyType::G2AddPIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                            term: G2AddTerm::PIndicator,
                        })
                    }
                    PolyType::G2AddXQC0 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::XQC0,
                    }),
                    PolyType::G2AddXQC1 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::XQC1,
                    }),
                    PolyType::G2AddYQC0 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::YQC0,
                    }),
                    PolyType::G2AddYQC1 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::YQC1,
                    }),
                    PolyType::G2AddQIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                            term: G2AddTerm::QIndicator,
                        })
                    }
                    PolyType::G2AddXRC0 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::XRC0,
                    }),
                    PolyType::G2AddXRC1 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::XRC1,
                    }),
                    PolyType::G2AddYRC0 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::YRC0,
                    }),
                    PolyType::G2AddYRC1 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::YRC1,
                    }),
                    PolyType::G2AddRIndicator => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                            term: G2AddTerm::RIndicator,
                        })
                    }
                    PolyType::G2AddLambdaC0 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::LambdaC0,
                    }),
                    PolyType::G2AddLambdaC1 => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::LambdaC1,
                    }),
                    PolyType::G2AddInvDeltaXC0 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                            term: G2AddTerm::InvDeltaXC0,
                        })
                    }
                    PolyType::G2AddInvDeltaXC1 => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                            term: G2AddTerm::InvDeltaXC1,
                        })
                    }
                    PolyType::G2AddIsDouble => VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                        term: G2AddTerm::IsDouble,
                    }),
                    PolyType::G2AddIsInverse => {
                        VirtualPolynomial::Recursion(RecursionPoly::G2Add {
                            term: G2AddTerm::IsInverse,
                        })
                    }
                    _ => return Fq::zero(),
                };
                accumulator.get_virtual_polynomial_claim(vp, SumcheckId::G2Add)
            } else if matches!(
                entry.poly_type,
                PolyType::MultiMillerLoopF
                    | PolyType::MultiMillerLoopFNext
                    | PolyType::MultiMillerLoopQuotient
                    | PolyType::MultiMillerLoopTXC0
                    | PolyType::MultiMillerLoopTXC1
                    | PolyType::MultiMillerLoopTYC0
                    | PolyType::MultiMillerLoopTYC1
                    | PolyType::MultiMillerLoopTXC0Next
                    | PolyType::MultiMillerLoopTXC1Next
                    | PolyType::MultiMillerLoopTYC0Next
                    | PolyType::MultiMillerLoopTYC1Next
                    | PolyType::MultiMillerLoopLambdaC0
                    | PolyType::MultiMillerLoopLambdaC1
                    | PolyType::MultiMillerLoopInvDeltaXC0
                    | PolyType::MultiMillerLoopInvDeltaXC1
                    | PolyType::MultiMillerLoopInvTwoYC0
                    | PolyType::MultiMillerLoopInvTwoYC1
                    | PolyType::MultiMillerLoopXP
                    | PolyType::MultiMillerLoopYP
                    | PolyType::MultiMillerLoopXQC0
                    | PolyType::MultiMillerLoopXQC1
                    | PolyType::MultiMillerLoopYQC0
                    | PolyType::MultiMillerLoopYQC1
                    | PolyType::MultiMillerLoopIsDouble
                    | PolyType::MultiMillerLoopIsAdd
                    | PolyType::MultiMillerLoopLVal
            ) {
                use crate::zkvm::witness::MultiMillerLoopTerm;
                let term = match entry.poly_type {
                    PolyType::MultiMillerLoopF => MultiMillerLoopTerm::F,
                    PolyType::MultiMillerLoopFNext => MultiMillerLoopTerm::FNext,
                    PolyType::MultiMillerLoopQuotient => MultiMillerLoopTerm::Quotient,
                    PolyType::MultiMillerLoopTXC0 => MultiMillerLoopTerm::TXC0,
                    PolyType::MultiMillerLoopTXC1 => MultiMillerLoopTerm::TXC1,
                    PolyType::MultiMillerLoopTYC0 => MultiMillerLoopTerm::TYC0,
                    PolyType::MultiMillerLoopTYC1 => MultiMillerLoopTerm::TYC1,
                    PolyType::MultiMillerLoopTXC0Next => MultiMillerLoopTerm::TXC0Next,
                    PolyType::MultiMillerLoopTXC1Next => MultiMillerLoopTerm::TXC1Next,
                    PolyType::MultiMillerLoopTYC0Next => MultiMillerLoopTerm::TYC0Next,
                    PolyType::MultiMillerLoopTYC1Next => MultiMillerLoopTerm::TYC1Next,
                    PolyType::MultiMillerLoopLambdaC0 => MultiMillerLoopTerm::LambdaC0,
                    PolyType::MultiMillerLoopLambdaC1 => MultiMillerLoopTerm::LambdaC1,
                    PolyType::MultiMillerLoopInvDeltaXC0 => MultiMillerLoopTerm::InvDeltaXC0,
                    PolyType::MultiMillerLoopInvDeltaXC1 => MultiMillerLoopTerm::InvDeltaXC1,
                    PolyType::MultiMillerLoopInvTwoYC0 => MultiMillerLoopTerm::InvTwoYC0,
                    PolyType::MultiMillerLoopInvTwoYC1 => MultiMillerLoopTerm::InvTwoYC1,
                    PolyType::MultiMillerLoopXP => MultiMillerLoopTerm::XP,
                    PolyType::MultiMillerLoopYP => MultiMillerLoopTerm::YP,
                    PolyType::MultiMillerLoopXQC0 => MultiMillerLoopTerm::XQC0,
                    PolyType::MultiMillerLoopXQC1 => MultiMillerLoopTerm::XQC1,
                    PolyType::MultiMillerLoopYQC0 => MultiMillerLoopTerm::YQC0,
                    PolyType::MultiMillerLoopYQC1 => MultiMillerLoopTerm::YQC1,
                    PolyType::MultiMillerLoopIsDouble => MultiMillerLoopTerm::IsDouble,
                    PolyType::MultiMillerLoopIsAdd => MultiMillerLoopTerm::IsAdd,
                    PolyType::MultiMillerLoopLVal => MultiMillerLoopTerm::LVal,
                    _ => return Fq::zero(),
                };
                let vp = VirtualPolynomial::Recursion(RecursionPoly::MultiMillerLoop {
                    term,
                    instance: entry.constraint_idx,
                });
                accumulator.get_virtual_polynomial_claim(vp, SumcheckId::MultiMillerLoop)
            } else {
                panic!("unexpected prefix-packing entry without a family tag: {entry:?}")
            }
        });

        // Append as a Fiat–Shamir message (matches existing Stage 3 transcript pattern).
        transcript.append_scalar(&packed_eval);

        // Register a committed opening on the packed dense polynomial.
        //
        // Opening points are stored in BIG_ENDIAN order for PCS verification.
        let opening_point: Vec<<Fq as JoltField>::Challenge> =
            r_full_lsb.into_iter().rev().map(|f| f.into()).collect();
        accumulator.append_dense(
            transcript,
            CommittedPolynomial::DoryDenseMatrix,
            SumcheckId::RecursionPacked,
            opening_point,
            packed_eval,
        );

        Ok(packed_eval)
    }
}
